version: 2

project_name: substack-cli

# Use conventional commits for determining the next version
before:
  hooks:
    - go mod tidy

git:
  # Parse conventional commits for version bumping
  prerelease_suffix: "-rc"
  # Ignore commits that don't affect the release
  ignore_tags:
    - "nightly"

builds:
  - id: substack-cli
    main: ./main.go
    binary: substack
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

brews:
  - repository:
      owner: aaron-srivastava
      name: substack-cli
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: substack-cli-bot
      email: substack-cli-bot@users.noreply.github.com
    commit_msg_template: "chore(brew): update formula for {{ .ProjectName }} {{ .Tag }} [skip ci]"
    directory: Formula
    caveats: |
      After installation, you need to authenticate with your Substack account:
        substack auth login
      For help, run:
        substack --help
    homepage: https://github.com/aaron-srivastava/substack-cli
    description: CLI tool for managing Substack publications
    license: MIT
    test: |
      system "#{bin}/substack", "--version"
    install: |
      bin.install "substack"

nfpms:
  - package_name: substack-cli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/aaron-srivastava/substack-cli
    description: CLI tool for managing Substack publications
    maintainer: Aaron Srivastava <aaron@example.com>
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: README.md
        dst: /usr/share/doc/substack-cli/README.md
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

release:
  github:
    owner: aaron-srivastava
    name: substack-cli
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
  header: .github/release-header.md.tmpl
  footer: .github/release-footer.md.tmpl

changelog:
  sort: asc
  groups:
    - title: "Features"
      regexp: "^feat(\\(.+\\))?!?:"
      order: 0
    - title: "Bug fixes"
      regexp: "^fix(\\(.+\\))?!?:"
      order: 1
    - title: "Performance"
      regexp: "^perf(\\(.+\\))?!?:"
      order: 2
    - title: "Refactoring"
      regexp: "^refactor(\\(.+\\))?!?:"
      order: 3
    - title: "Documentation"
      regexp: "^docs(\\(.+\\))?!?:"
      order: 4
    - title: "CI/CD"
      regexp: "^(ci|chore)(\\(.+\\))?!?:"
      order: 5
  filters:
    exclude:
      - "^test:"
      - Merge pull request
      - Merge branch

announce:
  bluesky:
    enabled: true
    username: "aaronsrivastava.com"
    message_template: "🚀 substack-cli {{.Tag}} released! {{.ReleaseURL}}"
