# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstackCli < Formula
  desc "CLI tool for managing Substack publications"
  homepage "https://github.com/aaron-srivastava/substack-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.0/substack-cli_v0.4.0_darwin_amd64.tar.gz"
      sha256 "4e9de42557e85380c63ccdc4c886b9f36c6d6aa16130d15acb8382dcb3bf9090"

      def install
        bin.install "substack"
      end
    end
    on_arm do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.0/substack-cli_v0.4.0_darwin_arm64.tar.gz"
      sha256 "0629db41b9a8f26c1e909b3ae91cc5ac0b7cc6cca459ef0ac36e5bb88d6c64dd"

      def install
        bin.install "substack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.0/substack-cli_v0.4.0_linux_amd64.tar.gz"
        sha256 "7338389c19640d04a9f673c287e36937bf99fe76fb0af2e5c301a1d45bbe4b69"

        def install
          bin.install "substack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.0/substack-cli_v0.4.0_linux_arm64.tar.gz"
        sha256 "88ace70115810faed208fd3ce0f3d9a5de77bb210d43bb1e27802d1c254a95eb"

        def install
          bin.install "substack"
        end
      end
    end
  end

  def caveats
    <<~EOS
      After installation, you need to authenticate with your Substack account:
        substack auth login
      For help, run:
        substack --help
    EOS
  end

  test do
    system "#{bin}/substack", "--version"
  end
end
