# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstackCli < Formula
  desc "CLI tool for managing Substack publications"
  homepage "https://github.com/aaron-srivastava/substack-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.0/substack-cli_v0.3.0_darwin_amd64.tar.gz"
      sha256 "45cceaa598ae3e83e24b09e64c3f55d3a9222f126d97f91dc7095a986ca284fc"

      def install
        bin.install "substack"
      end
    end
    on_arm do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.0/substack-cli_v0.3.0_darwin_arm64.tar.gz"
      sha256 "2dc59ed819c901b9d8eb8412e1149798d5208e1d77dcfecb117dd28eb5feb52e"

      def install
        bin.install "substack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.0/substack-cli_v0.3.0_linux_amd64.tar.gz"
        sha256 "0734e0b3c1b1b522720a55f3721d31c4f48b64916b826e37112521a11c7d1f86"

        def install
          bin.install "substack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.0/substack-cli_v0.3.0_linux_arm64.tar.gz"
        sha256 "9f4d56930c45f2a9cffa6612f1666161d46a20080e22dd5b33d4a24af346ef9f"

        def install
          bin.install "substack"
        end
      end
    end
  end

  def caveats
    <<~EOS
      After installation, you need to authenticate with your Substack account:
        substack auth login
      For help, run:
        substack --help
    EOS
  end

  test do
    system "#{bin}/substack", "--version"
  end
end
