# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstackCli < Formula
  desc "CLI tool for managing Substack publications"
  homepage "https://github.com/aaron-srivastava/substack-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.1/substack-cli_v0.3.1_darwin_amd64.tar.gz"
      sha256 "584f8893798210420647588647ae60b224af5bb6cb3198474e5d3c088c805266"

      def install
        bin.install "substack"
      end
    end
    on_arm do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.1/substack-cli_v0.3.1_darwin_arm64.tar.gz"
      sha256 "72e48943c046e11ad71562714b95fe8eb594468795b65a22672cc5ff66dcacc2"

      def install
        bin.install "substack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.1/substack-cli_v0.3.1_linux_amd64.tar.gz"
        sha256 "a26e42fba05294c1a201fc334beea5ae884f012c07ca79a8dc765d96e8dd63f7"

        def install
          bin.install "substack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.3.1/substack-cli_v0.3.1_linux_arm64.tar.gz"
        sha256 "2172bf6539dc43667030916028855889b25a1b27243e9e406029fbcbdd3e4b44"

        def install
          bin.install "substack"
        end
      end
    end
  end

  def caveats
    <<~EOS
      After installation, you need to authenticate with your Substack account:
        substack auth login
      For help, run:
        substack --help
    EOS
  end

  test do
    system "#{bin}/substack", "--version"
  end
end
