# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstackCli < Formula
  desc "CLI tool for managing Substack publications"
  homepage "https://github.com/aaron-srivastava/substack-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.1/substack-cli_v0.4.1_darwin_amd64.tar.gz"
      sha256 "b28ab638a96e10ba8000c327770ec6f1f6b671fd05a1032e2a672e1220a6efcc"

      def install
        bin.install "substack"
      end
    end
    on_arm do
      url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.1/substack-cli_v0.4.1_darwin_arm64.tar.gz"
      sha256 "9ad25e6075532f8572392222ffb612d28264fa306b0a3e99e21b9a05c58028cf"

      def install
        bin.install "substack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.1/substack-cli_v0.4.1_linux_amd64.tar.gz"
        sha256 "81ed03715c6d13329a30d8d36aa35886134b430ffa0e2f15c0ec3aa72dd98100"

        def install
          bin.install "substack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron-srivastava/substack-cli/releases/download/v0.4.1/substack-cli_v0.4.1_linux_arm64.tar.gz"
        sha256 "a8c2a9476e90f28382f8926fc6e6967584d372bd4b3cbd6c8c0e1dc2534f905a"

        def install
          bin.install "substack"
        end
      end
    end
  end

  def caveats
    <<~EOS
      After installation, you need to authenticate with your Substack account:
        substack auth login
      For help, run:
        substack --help
    EOS
  end

  test do
    system "#{bin}/substack", "--version"
  end
end
